
WINDOW_LOG_EVENTS = {
1100 : "The event logging service has shut down",
1101 : "Audit events have been dropped by the transport.",
1102 : "The audit log was cleared",
1104 : "The security Log is now full",
1108 : "The event logging service encountered an error",
4612 : "Internal resources allocated for the queuing of audit messages have been exhausted, leading to the loss of some audits.",
4616 : "The system time was changed.",
4618 : "A monitored security event pattern has occurred",
4621 : "Administrator recovered system from CrashOnAuditFail",
4625 : "An account failed to log on",
4646 : "IKE DoS-prevention mode started",
4649 : "A replay attack was detected",
4657 : "A registry value was modified",
4672 : "Special privileges assigned to new logon",
4704 : "A user right was assigned",
4710 : "IPsec Services was disabled",
4712 : "IPsec Services encountered a potentially serious failure",
4713 : "Kerberos policy was changed",
4714 : "Encrypted data recovery policy was changed",
4717 : "System security access was granted to an account",
4718 : "System security access was removed from an account",
4719 : "System audit policy was changed",
4720 : "A user account was created",
4722 : "A user account was enabled",
4723 : "An attempt was made to change an account's password",
4724 : "An attempt was made to reset an accounts password",
4725 : "A user account was disabled",
4726 : "A user account was deleted",
4727 : "A security-enabled global group was created",
4728 : "A member was added to a security-enabled global group",
4729 : "A member was removed from a security-enabled global group",
4730 : "A security-enabled global group was deleted",
4731 : "A security-enabled local group was created",
4732 : "A member was added to a security-enabled local group",
4733 : "A member was removed from a security-enabled local group",
4734 : "A security-enabled local group was deleted",
4735 : "A security-enabled local group was changed",
4737 : "A security-enabled global group was changed",
4739 : "Domain Policy was changed",
4740 : "A user account was locked out",
4741 : "A computer account was created",
4742 : "A computer account was changed",
4743 : "A computer account was deleted",
4744 : "A security-disabled local group was created",
4745 : "A security-disabled local group was changed",
4746 : "A member was added to a security-disabled local group",
4747 : "A member was removed from a security-disabled local group",
4748 : "A security-disabled local group was deleted",
4749 : "A security-disabled global group was created",
4750 : "A security-disabled global group was changed",
4751 : "A member was added to a security-disabled global group",
4752 : "A member was removed from a security-disabled global group",
4753 : "A security-disabled global group was deleted",
4754 : "A security-enabled universal group was created",
4755 : "A security-enabled universal group was changed",
4756 : "A member was added to a security-enabled universal group",
4757 : "A member was removed from a security-enabled universal group",
4758 : "A security-enabled universal group was deleted",
4759 : "A security-disabled universal group was created",
4760 : "A security-disabled universal group was changed",
4761 : "A member was added to a security-disabled universal group",
4762 : "A member was removed from a security-disabled universal group",
4763 : "A security-disabled universal group was deleted",
4767 : "A user account was unlocked",
4771 : "Kerberos pre-authentication failed",
4772 : "A Kerberos authentication ticket request failed",
4773 : "A Kerberos service ticket request failed",
4775 : "An account could not be mapped for logon",
4777 : "The domain controller failed to validate the credentials for an account",
4782 : "The password hash an account was accessed",
4794 : "An attempt was made to set the Directory Services Restore Mode administrator password",
4797 : "An attempt was made to query the existence of a blank password for an account",
4798 : "A user's local group membership was enumerated.",
4799 : "A security-enabled local group membership was enumerated",
4816 : "RPC detected an integrity violation while decrypting an incoming message",
4817 : "Auditing settings on object were changed.",
4819 : "Central Access Policies on the machine have been changed",
4820 : "A Kerberos Ticket-granting-ticket (TGT) was denied because the device does not meet the access control restrictions",
4821 : "A Kerberos service ticket was denied because the user, device, or both does not meet the access control restrictions",
4822 : "NTLM authentication failed because the account was a member of the Protected User group",
4823 : "NTLM authentication failed because access control restrictions are required",
4824 : "Kerberos preauthentication by using DES or RC4 failed because the account was a member of the Protected User group",
4825 : "A user was denied the access to Remote Desktop. By default, users are allowed to connect only if they are members of the Remote Desktop Users group or Administrators group",
4868 : "The certificate manager denied a pending certificate request",
4882 : "The security permissions for Certificate Services changed",
4884 : "Certificate Services imported a certificate into its database",
4908 : "Special Groups Logon table modified",
4947 : "A change has been made to Windows Firewall exception list. A rule was modified",
4948 : "A change has been made to Windows Firewall exception list. A rule was deleted",
4950 : "A Windows Firewall setting has changed",
4953 : "A rule has been ignored by Windows Firewall because it could not parse the rule",
4954 : "Windows Firewall Group Policy settings has changed. The new settings have been applied",
4960 : "IPsec dropped an inbound packet that failed an integrity check",
4961 : "IPsec dropped an inbound packet that failed a replay check",
4962 : "IPsec dropped an inbound packet that failed a replay check",
4963 : "IPsec dropped an inbound clear text packet that should have been secured",
4964 : "Special groups have been assigned to a new logon",
4965 : "IPsec received a packet from a remote computer with an incorrect Security Parameter Index (SPI).",
4976 : "During Main Mode negotiation, IPsec received an invalid negotiation packet.",
4977 : "During Quick Mode negotiation, IPsec received an invalid negotiation packet.",
4978 : "During Extended Mode negotiation, IPsec received an invalid negotiation packet.",
5025 : "The Windows Firewall Service has been stopped",
5027 : "The Windows Firewall Service was unable to retrieve the security policy from the local storage",
5028 : "The Windows Firewall Service was unable to parse the new security policy.",
5030 : "The Windows Firewall Service failed to start",
5038 : "Code integrity determined that the image hash of a file is not valid",
5041 : "A change has been made to IPsec settings. An Authentication Set was modified",
5042 : "A change has been made to IPsec settings. An Authentication Set was deleted",
5044 : "A change has been made to IPsec settings. A Connection Security Rule was modified",
5045 : "A change has been made to IPsec settings. A Connection Security Rule was deleted",
5047 : "A change has been made to IPsec settings. A Crypto Set was modified",
5048 : "A change has been made to IPsec settings. A Crypto Set was deleted",
5049 : "An IPsec Security Association was deleted",
5050 : "An attempt to programmatically disable the Windows Firewall using a call to INetFwProfile.FirewallEnabled",
5057 : "A cryptographic primitive operation failed",
5060 : "Verification operation failed",
5124 : "A security setting was updated on OCSP Responder Service",
5146 : "The Windows Filtering Platform has blocked a packet",
5147 : "A more restrictive Windows Filtering Platform filter has blocked a packet",
5148 : "The Windows Filtering Platform has detected a DoS attack and entered a defensive mode; packets associated with this attack will be discarded.",
5149 : "The DoS attack has subsided and normal processing is being resumed.",
5150 : "The Windows Filtering Platform has blocked a packet.",
5151 : "A more restrictive Windows Filtering Platform filter has blocked a packet.",
5152 : "The Windows Filtering Platform blocked a packet",
5153 : "A more restrictive Windows Filtering Platform filter has blocked a packet",
5157 : "The Windows Filtering Platform has blocked a connection",
5484 : "IPsec Services has experienced a critical failure and has been shut down",
6273 : "Network Policy Server denied access to a user",
6276 : "Network Policy Server quarantined a user",
6279 : "Network Policy Server locked the user account due to repeated failed authentication attempts",
6281 : "Code Integrity determined that the page hashes of an image file are not valid...",
6410 : "Code integrity determined that a file does not meet the security requirements to load into a process. This could be due to the use of shared sections or other issues",
6418 : "The FIPS mode crypto selftests failed",
6423 : "The installation of this device is forbidden by system policy",
6424 : "The installation of this device was allowed, after having previously been forbidden by policy",
8191 : "Highest System-Defined Audit Message Value"
}


class WindowsLogAnalysis:

    def analyze_logs(self):

        values = [
            {1: "B", 2: "D"}
        ]

        print("analyzing logs")